# Scan this file for changes every 30 seconds
refresh_rate = 30

# An appender named "stdout" that writes to stdout
[appenders.stdout]
kind = "console"
pattern = "[%l] %M (%f:%L) - %m"

# Database logs
[appenders.db]
kind = "file"
path = "logs/db.log"
pattern = "%d - %l - %M (%f:%L) - %m"

# Server logs
[appenders.server]
kind = "file"
path = "logs/server.log"

[root]
level = "info"
appenders = ["stdout"]

[loggers."nestedworld_db"]
level = "info"
appenders = ["db"]

[loggers."nestedworld_server"]
level = "debug"
appenders = ["server"]
