[package]
name = "nestedworld-server"
version = "0.1.0"
authors = ["KokaKiwi <kokakiwi@kokakiwi.net>"]

[dependencies]
chan = "0.1.14"
clippy = { version = "*", optional = true }
log = "0.3.5"
mioco = "0.5.0"
nestedworld-db = { path = "../db" }
rmp = "^0.7"
serde = "^0.7"
serde_macros = "^0.7"
quick-error = "1.0.0"
