[package]
name = "nestedworld-server"
version = "0.1.0"
authors = ["KokaKiwi <kokakiwi@kokakiwi.net>"]

[dependencies]
chan = "0.1.14"
hyper = "0.8.0"
log = "0.3.5"
mio = "0.5.0"
nestedworld-db = { path = "../db" }
rmp = "0.7.3"
quick-error = "1.0.0"
