= Message format

The protocol is composed of messages formatted as https://msgpack.org[MessagePack] objects.

A message is MessagePack object containing message data in the fields.

All messages have some common fields:

[cols="15,20,65"]
|===
| Field name | Field type | Description

| `type`     | `string`   | *(required)* The message type, with the reserved name `result` for "responses"
| `id`       | `string`   | *(optional)* An optional request ID used in request to track responses. +
                            If provided by a request, the response _MUST_ include the same ID.

|===

.Example
[source,json]
----
# Client -> Server
{
    "id": "c791aeb9-d9bd-4845-acb1-787d9f1d6dff", # <1>
    "type": "chat:join-channel", # <2>
    "channel": "general"
}
# Server -> Client
{
    "id": "c791aeb9-d9bd-4845-acb1-787d9f1d6dff", # <3>
    "type": "result",
    "result": "success",
    "users": []
}
----
<1> An ID generated by the client to identify the request
<2> The request type, here `<<msg-chat-join-channel,chat:join-channel>>` for the example
<3> The ID sent in the request by the client

= States

A message state represents the context in which a message is sent (authenticated, in combat, etc.)

This state is defined by specifics message fields and/or a previous sent message (in which case the state is associated with
the connection)

In case a message is sent without the required state associated or with invalid state data, some errors specific to the
state can be generated.

IMPORTANT: A message modifying the state associated with the connection _WILL_ be explicitely documented as it.

= Special messages

Some common messages with not specific context related to them.

[[msg-result]]
== `result`

This message is sent in response to a request message (all other message types are requests) when the request
need only a binary response (i.e. `ok` or `error`)

WARNING: All requests are not always followed by a response.

.Fields
[cols="15,20,65"]
|===
| Field name | Field type | Description

| `result`   | `string`   | *(required)* The result type: `success` or `error`

|===

In case of success, the other message fields contains the response data.

In case of error, the message contains special fields, and the other fields are the error details:

.Error fields
[cols="15,20,65"]
|===
| Field name | Field type | Description

| `kind`     | `string`   | *(required)* An identifier which identify the "kind" of error.
| `message`  | `string`   | *(required)* A formatted error message which describe the error.

|===

.Success example
[source,json]
----
{
    "type": "result",
    "result": "success"
}
----

.Error example
[source,json]
----
{
    "type": "result",
    "result": "error",
    "kind": "NotAuthenticated",
    "message": "You are not authenticated"
}
----
