= Message format

The protocol is composed of messages formatted as MessagePack footnote:[https://msgpack.org] objects.

A message is MessagePack object containing message data in the fields.

All messages have some common fields:

[cols="15,20,65"]
|===
| Field name | Field type | Description

| `type`     | `string`   | *(required)* The message type, with the reserved name `result` for "responses"
| `id`       | `string`   | *(optional)* An optional request ID used in request to track responses. +
                            If provided by a request, the response _MUST_ include the same ID.

|===

.Example
[source,json]
----
# Client -> Server
{
    "id": "c791aeb9-d9bd-4845-acb1-787d9f1d6dff", # <1>
    "type": "chat:join-channel", # <2>
    "token": "mt11MwyHz0wO2Kz0nQlcl6T4hmWGzTkk", # <3>
    "channel": "general"
}
# Server -> Client
{
    "id": "c791aeb9-d9bd-4845-acb1-787d9f1d6dff", # <4>
    "type": "result",
    "result": "success",
    "users": []
}
----
<1> An ID generated by the client to identify the request
<2> The request type, here `<<msg-chat-join-channel,chat:join-channel>>` for the example
<3> The token needed by the `<<state-authenticated,authenticated>>` state
<4> The ID sent in the request by the client

= States

A message state represents the "context" in which a message is sent, characterized by specifics message fields.

In case a message is sent without its state fields, or with invalid fields, some errors specific to the state can be
generated.

[[state-authenticated]]
== `authenticated`

A message with the state `authenticated` contains informations about a logged user context.

.Fields
[cols="15,20,65"]
|===
| Field name | Field type | Description

| `token`    | `string`   | *(required)* The session token, given by the REST API

|===

.Errors
* `NotAuthenticated`: The token is invalid

= Special messages

Some common messages with not specific context related to them.

[[msg-result]]
== `result`

This message is sent in response to a request message (all other message types are requests) when the request
need only a binary response (i.e. `ok` or `error`)

WARNING: All requests are not always followed by a response.

.Fields
[cols="15,20,65"]
|===
| Field name | Field type | Description

| `result`   | `string`   | *(required)* The result type: `success` or `error`

|===

In case of success, the other message fields contains the response data.

In case of error, the message contains special fields, and the other fields are the error details:

.Error fields
[cols="15,20,65"]
|===
| Field name | Field type | Description

| `kind`     | `string`   | *(required)* An identifier which identify the "kind" of error.
| `message`  | `string`   | *(required)* A formatted error message which describe the error.

|===

.Success example
[source,json]
----
{
    "type": "result",
    "result": "success"
}
----

.Error example
[source,json]
----
{
    "type": "result",
    "result": "error",
    "kind": "NotAuthenticated",
    "message": "You are not authenticated"
}
----
